FROM qwenllm/qwen3-asr:latest

COPY models/qwen3-asr-1.7b /models/qwen3-asr-1.7b

ENTRYPOINT ["qwen-asr-serve"]
CMD ["/models/qwen3-asr-1.7b", "--served-model-name", "Qwen/Qwen3-ASR-1.7B", "--host", "0.0.0.0", "--port", "8000", "--gpu-memory-utilization", "0.70", "--max-model-len", "32768"]
