apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - qwen3-asr.yaml
  - amphion-spec.yaml
  - gateway.yaml
  - ingress.yaml
configMapGenerator:
  - name: audiollm-qwen-only-config
    namespace: audiollm
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
