# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import diarization_pb2 as diarization__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in diarization_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiarizationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Diarize = channel.stream_stream(
                '/diarization.v1.DiarizationService/Diarize',
                request_serializer=diarization__pb2.DiarizationRequest.SerializeToString,
                response_deserializer=diarization__pb2.DiarizationEvent.FromString,
                _registered_method=True)
        self.Healthz = channel.unary_unary(
                '/diarization.v1.DiarizationService/Healthz',
                request_serializer=diarization__pb2.HealthzRequest.SerializeToString,
                response_deserializer=diarization__pb2.HealthzResponse.FromString,
                _registered_method=True)


class DiarizationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Diarize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Healthz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiarizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Diarize': grpc.stream_stream_rpc_method_handler(
                    servicer.Diarize,
                    request_deserializer=diarization__pb2.DiarizationRequest.FromString,
                    response_serializer=diarization__pb2.DiarizationEvent.SerializeToString,
            ),
            'Healthz': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthz,
                    request_deserializer=diarization__pb2.HealthzRequest.FromString,
                    response_serializer=diarization__pb2.HealthzResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'diarization.v1.DiarizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('diarization.v1.DiarizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiarizationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Diarize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/diarization.v1.DiarizationService/Diarize',
            diarization__pb2.DiarizationRequest.SerializeToString,
            diarization__pb2.DiarizationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Healthz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/diarization.v1.DiarizationService/Healthz',
            diarization__pb2.HealthzRequest.SerializeToString,
            diarization__pb2.HealthzResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
